/**
 * User: Charles
 * Date: 11/9/12
 *
 *

 The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28

 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?

 *
 */

public class Problem12 implements Solveable {

    public Long solve() {

        int numberOfDivisors = 0;
        long triangleNumber = 0;
        int adder = 1;

        while (numberOfDivisors < 500) {
            triangleNumber = (triangleNumber + adder);
            if (triangleNumber % 2 == 0 && triangleNumber % 3 == 0 && triangleNumber % 5 == 0) {
                numberOfDivisors = numberOfDivisors(triangleNumber);
            }
            adder++;
        }

        return triangleNumber;
    }

    private int numberOfDivisors(long number) {
        int divisorsSoFar = 2;
        for(long num = 2; num <= Math.sqrt(number); num++) {
            if(number % num == 0) {
                divisorsSoFar +=2;
            }
        }
        return divisorsSoFar;
    }
}
