/**
 * User: Charles
 * Date: 4/10/12
 * <p/>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem2 implements Solveable {

    public Double solve() {
        Double answer = 0.0;
        double first = 1, second = 2, sum = 0;

        while (sum <= 4000000) {

            sum = first + second;

            if (sum % 2 == 0) {
                answer += sum;
            }

            first = second;
            second = sum;
        }

        return answer + 2;
    }

}
